import streamlit as st
import requests
import io
from PIL import Image

# 1. Configuration
# IMPORTANT: Ensure this matches the 'Direct URL' from Hugging Face
BACKEND_URL = "https://poras-nehra-deploy.hf.space/generate"

st.set_page_config(page_title="My Custom AI Artist", page_icon="🎨")
st.title("🎨 My Custom AI Artist")

# 2. Initialize Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []

# 3. Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message["role"] == "user":
            st.markdown(message["content"])
        else:
            st.image(message["content"], caption="Generated by my model")

# 4. Handle User Input
if prompt := st.chat_input("What should I draw for you?"):
    # Add user message to history
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # 5. Call the Backend
    with st.chat_message("assistant"):
        with st.spinner("The AI is painting... (This can take 2-4 minutes on Free CPU)"):
            try:
                # Added timeout=300 (5 minutes) because CPU generation is slow
                response = requests.post(
                    BACKEND_URL, 
                    json={"prompt": prompt}, 
                    timeout=300 
                )
                
                if response.status_code == 200:
                    # Convert raw bytes from API into a displayable Image
                    image_bytes = io.BytesIO(response.content)
                    generated_image = Image.open(image_bytes)
                    
                    # Display the image
                    st.image(generated_image, caption=f"Prompt: {prompt}")
                    
                    # Save image to history
                    st.session_state.messages.append({"role": "assistant", "content": generated_image})
                else:
                    st.error(f"Backend Error: {response.status_code} - {response.text}")
            
            except requests.exceptions.Timeout:
                st.error("The request timed out. The AI is still working, but the connection closed. Try a simpler prompt!")
            except Exception as e:
                # This is where your previous error was showing
                st.error(f"Connection Failed: Ensure your Hugging Face Space is 'Running'! Details: {e}")
