import streamlit as st
import requests
import io
from PIL import Image

# 1. Configuration - Replace with your NGROK URL if using Colab
BACKEND_URL = "http://127.0.0.1:8000"

st.set_page_config(page_title="My Custom AI Artist", page_icon="🎨")
st.title("🎨 My Custom AI Artist")

# 2. Initialize Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []

# 3. Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message["role"] == "user":
            st.markdown(message["content"])
        else:
            # If it's the assistant, show the image that was generated
            st.image(message["content"], caption="Generated by my model")

# 4. Handle User Input
if prompt := st.chat_input("What should I draw for you?"):
    # Add user message to history
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # 5. Call the Backend
    with st.chat_message("assistant"):
        with st.spinner("Thinking and Painting..."):
            try:
                # We send the prompt as JSON
                response = requests.post(BACKEND_URL, json={"prompt": prompt})
                
                if response.status_code == 200:
                    # Convert raw bytes from API into a displayable Image
                    image_bytes = io.BytesIO(response.content)
                    generated_image = Image.open(image_bytes)
                    
                    # Display the image
                    st.image(generated_image, caption=f"Prompt: {prompt}")
                    
                    # Save image to history (store the PIL object or bytes)
                    st.session_state.messages.append({"role": "assistant", "content": generated_image})
                else:
                    st.error(f"Backend Error: {response.text}")
            except Exception as e:
                st.error(f"Connection Failed: Ensure your backend is running! ({e})")